// Generated by gencpp from file count/contResponse.msg
// DO NOT EDIT!


#ifndef COUNT_MESSAGE_CONTRESPONSE_H
#define COUNT_MESSAGE_CONTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace count
{
template <class ContainerAllocator>
struct contResponse_
{
  typedef contResponse_<ContainerAllocator> Type;

  contResponse_()
    : count(0)  {
    }
  contResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef uint32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::count::contResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::count::contResponse_<ContainerAllocator> const> ConstPtr;

}; // struct contResponse_

typedef ::count::contResponse_<std::allocator<void> > contResponse;

typedef boost::shared_ptr< ::count::contResponse > contResponsePtr;
typedef boost::shared_ptr< ::count::contResponse const> contResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::count::contResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::count::contResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::count::contResponse_<ContainerAllocator1> & lhs, const ::count::contResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::count::contResponse_<ContainerAllocator1> & lhs, const ::count::contResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace count

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::count::contResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::count::contResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count::contResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count::contResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count::contResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count::contResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::count::contResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac8b22eb02c1f433e0a55ee9aac59a18";
  }

  static const char* value(const ::count::contResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac8b22eb02c1f433ULL;
  static const uint64_t static_value2 = 0xe0a55ee9aac59a18ULL;
};

template<class ContainerAllocator>
struct DataType< ::count::contResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "count/contResponse";
  }

  static const char* value(const ::count::contResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::count::contResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 count\n"
;
  }

  static const char* value(const ::count::contResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::count::contResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct contResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::count::contResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::count::contResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COUNT_MESSAGE_CONTRESPONSE_H
