// Generated by gencpp from file count/contRequest.msg
// DO NOT EDIT!


#ifndef COUNT_MESSAGE_CONTREQUEST_H
#define COUNT_MESSAGE_CONTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace count
{
template <class ContainerAllocator>
struct contRequest_
{
  typedef contRequest_<ContainerAllocator> Type;

  contRequest_()
    : words()  {
    }
  contRequest_(const ContainerAllocator& _alloc)
    : words(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _words_type;
  _words_type words;





  typedef boost::shared_ptr< ::count::contRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::count::contRequest_<ContainerAllocator> const> ConstPtr;

}; // struct contRequest_

typedef ::count::contRequest_<std::allocator<void> > contRequest;

typedef boost::shared_ptr< ::count::contRequest > contRequestPtr;
typedef boost::shared_ptr< ::count::contRequest const> contRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::count::contRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::count::contRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::count::contRequest_<ContainerAllocator1> & lhs, const ::count::contRequest_<ContainerAllocator2> & rhs)
{
  return lhs.words == rhs.words;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::count::contRequest_<ContainerAllocator1> & lhs, const ::count::contRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace count

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::count::contRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::count::contRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count::contRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::count::contRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count::contRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::count::contRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::count::contRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f897d3845272d18053a750c1cfb862a";
  }

  static const char* value(const ::count::contRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f897d3845272d18ULL;
  static const uint64_t static_value2 = 0x053a750c1cfb862aULL;
};

template<class ContainerAllocator>
struct DataType< ::count::contRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "count/contRequest";
  }

  static const char* value(const ::count::contRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::count::contRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string words\n"
;
  }

  static const char* value(const ::count::contRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::count::contRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.words);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct contRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::count::contRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::count::contRequest_<ContainerAllocator>& v)
  {
    s << indent << "words: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.words);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COUNT_MESSAGE_CONTREQUEST_H
